# Women's local area data
## Checking factsheets

In [38]:
%load_ext autoreload
%autoreload 2

In [39]:
import pandas as pd
import numpy as np
import random
import math
import src.utilities as utils
import src.test.check_factsheets as check_factsheets
from src.data.processing.combine_custody_pfa_population import load_data

In [3]:
utils.setup_logging()
config = utils.read_config()

In [5]:
custody_data, population_data = load_data()

2025-09-15 14:52:31,956 - INFO - Loaded data from data/processed/PFA_custodial_sentences_all_FINAL.csv
2025-09-15 14:52:32,091 - INFO - Loaded data from data/interim/LA_PFA_population_women_2011-2023.csv

In [6]:
custody_data.head()

,pfa,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,per_change_2014
0,Avon and Somerset,196,168,165,106,151,153,107,94,113,120,153,-0.219388
1,Bedfordshire,72,80,57,46,41,34,25,19,37,40,35,-0.513889
2,Cambridgeshire,93,92,119,102,117,90,76,47,69,81,83,-0.107527
3,Cheshire,168,179,165,148,160,139,120,102,65,108,96,-0.428571
4,Cleveland,113,90,121,129,161,101,55,96,96,140,192,0.699115

## Calculating sample size for review

In [28]:
N = len(custody_data['pfa'].unique())
z = 1.96  # 95% confidence
p = 0.5   # maximum variability
e = 0.2   # 20% margin of error

n = (N * z**2 * p * (1-p)) / ((N-1)*e**2 + z**2*p*(1-p))
print(f"Recommended sample size: {math.ceil(n)}")

Recommended sample size: 16

In [30]:
random_pfas = random.sample(list(custody_data['pfa']), math.ceil(n))
print(random_pfas)

['West Mercia', 'West Midlands', 'Surrey', 'North Yorkshire', 'Derbyshire', 'Staffordshire', 'North Wales', 'Humberside', 'London', 'Devon and Cornwall', 'Norfolk', 'Dyfed Powys', 'Hertfordshire', 'Gwent', 'Wiltshire', 'West Yorkshire']

In [37]:
filt = custody_data['pfa'].isin(random_pfas)
cols = list(custody_data.columns[:2]) + list(custody_data.columns[-3:])
custody_data.loc[filt, cols]

                   pfa  2014  2023  2024  per_change_2014
6           Derbyshire   165   110   112        -0.321212
7   Devon and Cornwall   116    88   118         0.017241
10         Dyfed Powys    18    24    10        -0.444444
14               Gwent    56    31    52        -0.071429
16       Hertfordshire    86    55    54        -0.372093
17          Humberside   149   127   141        -0.053691
22              London  1297   583   701        -0.459522
24             Norfolk    85    87    73        -0.141176
25         North Wales    91    85    68        -0.252747
26     North Yorkshire    70    65    76         0.085714
32       Staffordshire   124    85    91        -0.266129
34              Surrey    98    27    33        -0.663265
38         West Mercia   112    64    57        -0.491071
39       West Midlands   473   272   313        -0.338266
40      West Yorkshire   298   349   402         0.348993
41           Wiltshire    33    37    32        -0.030303

## Testing script up to this point

In [41]:
check_factsheets.main()

2025-09-15 16:07:20,685 - INFO - Loaded data from data/processed/PFA_custodial_sentences_all_FINAL.csv
2025-09-15 16:07:20,710 - INFO - Loaded data from data/interim/LA_PFA_population_women_2011-2023.csv

Recommended sample size: 16
Randomly selected PFAs for review:
                 pfa  2014  2023  2024  per_change_2014
1       Bedfordshire    72    40    35        -0.513889
4          Cleveland   113   140   192         0.699115
5            Cumbria    85    53    68        -0.200000
6         Derbyshire   165   110   112        -0.321212
8             Dorset    58    47    44        -0.241379
11             Essex   199    93    92        -0.537688
17        Humberside   149   127   141        -0.053691
20    Leicestershire   101    80    84        -0.168317
21      Lincolnshire    45    55    50         0.111111
22            London  1297   583   701        -0.459522
27  Northamptonshire    93    62    72        -0.225806
32     Staffordshire   124    85    91        -0.266129
34            Surrey    98    27    33        -0.663265
38       West Mercia   112    64    57        -0.491071
40    West Yorkshire   298   349   402         0.348993
41         Wiltshire    33    37    32        -0.030303