# Women's local area data
## Checking factsheets

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np
import random
import math
import src.utilities as utils
import src.test.check_factsheets as check_factsheets
from src.data.processing.combine_custody_pfa_population import load_data

In [3]:
utils.setup_logging()
config = utils.read_config()

In [5]:
custody_data, population_data = load_data()

2025-09-15 14:52:31,956 - INFO - Loaded data from data/processed/PFA_custodial_sentences_all_FINAL.csv
2025-09-15 14:52:32,091 - INFO - Loaded data from data/interim/LA_PFA_population_women_2011-2023.csv

In [6]:
custody_data.head()

,pfa,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,per_change_2014
0,Avon and Somerset,196,168,165,106,151,153,107,94,113,120,153,-0.219388
1,Bedfordshire,72,80,57,46,41,34,25,19,37,40,35,-0.513889
2,Cambridgeshire,93,92,119,102,117,90,76,47,69,81,83,-0.107527
3,Cheshire,168,179,165,148,160,139,120,102,65,108,96,-0.428571
4,Cleveland,113,90,121,129,161,101,55,96,96,140,192,0.699115

## Calculating sample size for review

In [28]:
N = len(custody_data['pfa'].unique())
z = 1.96  # 95% confidence
p = 0.5   # maximum variability
e = 0.2   # 20% margin of error

n = (N * z**2 * p * (1-p)) / ((N-1)*e**2 + z**2*p*(1-p))
print(f"Recommended sample size: {math.ceil(n)}")

Recommended sample size: 16

In [30]:
random_pfas = random.sample(list(custody_data['pfa']), math.ceil(n))
print(random_pfas)

['West Mercia', 'West Midlands', 'Surrey', 'North Yorkshire', 'Derbyshire', 'Staffordshire', 'North Wales', 'Humberside', 'London', 'Devon and Cornwall', 'Norfolk', 'Dyfed Powys', 'Hertfordshire', 'Gwent', 'Wiltshire', 'West Yorkshire']

In [37]:
filt = custody_data['pfa'].isin(random_pfas)
cols = list(custody_data.columns[:2]) + list(custody_data.columns[-3:])
custody_data.loc[filt, cols]

                   pfa  2014  2023  2024  per_change_2014
6           Derbyshire   165   110   112        -0.321212
7   Devon and Cornwall   116    88   118         0.017241
10         Dyfed Powys    18    24    10        -0.444444
14               Gwent    56    31    52        -0.071429
16       Hertfordshire    86    55    54        -0.372093
17          Humberside   149   127   141        -0.053691
22              London  1297   583   701        -0.459522
24             Norfolk    85    87    73        -0.141176
25         North Wales    91    85    68        -0.252747
26     North Yorkshire    70    65    76         0.085714
32       Staffordshire   124    85    91        -0.266129
34              Surrey    98    27    33        -0.663265
38         West Mercia   112    64    57        -0.491071
39       West Midlands   473   272   313        -0.338266
40      West Yorkshire   298   349   402         0.348993
41           Wiltshire    33    37    32        -0.030303

## Testing script up to this point

In [3]:
sample_pfas = check_factsheets.build_sample_pfa_list()
sample_pfas

2025-09-25 15:05:17,467 - INFO - Loading sentence length data...
2025-09-25 15:05:17,496 - INFO - Loaded data from data/processed/PFA_custodial_sentences_all_FINAL.csv

['North Wales',
 'Thames Valley',
 'Devon and Cornwall',
 'Humberside',
 'Warwickshire',
 'Kent',
 'London',
 'Nottinghamshire',
 'Sussex',
 'Cumbria',
 'Cambridgeshire',
 'Leicestershire',
 'Essex',
 'South Yorkshire',
 'Surrey',
 'Bedfordshire']

In [8]:
all_custody_data = check_factsheets.load_data(data_type='sentence_length', sentence_length='all')
all_custody_data.head()

2025-09-25 15:09:20,480 - INFO - Loading sentence length data...
2025-09-25 15:09:20,490 - INFO - Loaded data from data/processed/PFA_custodial_sentences_all_FINAL.csv

,pfa,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,per_change_2014
0,Avon and Somerset,196,168,165,106,151,153,107,94,113,120,153,-0.219388
1,Bedfordshire,72,80,57,46,41,34,25,19,37,40,35,-0.513889
2,Cambridgeshire,93,92,119,102,117,90,76,47,69,81,83,-0.107527
3,Cheshire,168,179,165,148,160,139,120,102,65,108,96,-0.428571
4,Cleveland,113,90,121,129,161,101,55,96,96,140,192,0.699115

In [ ]:
all_custody_df = check_factsheets.create_total_custodial_sentences_table(all_custody_data, sample_pfas)
all_custody_df

2025-09-25 15:09:23,517 - INFO - Saving...
2025-09-25 15:09:23,524 - INFO - Data successfully saved to data/tests/factsheet_custodial_sentences_all.csv

                   pfa  2014  2023  2024  per_change_2014
1         Bedfordshire    72    40    35        -0.513889
2       Cambridgeshire    93    81    83        -0.107527
5              Cumbria    85    53    68        -0.200000
7   Devon and Cornwall   116    88   118         0.017241
11               Essex   199    93    92        -0.537688
17          Humberside   149   127   141        -0.053691
18                Kent   196   133   156        -0.204082
20      Leicestershire   101    80    84        -0.168317
22              London  1297   583   701        -0.459522
25         North Wales    91    85    68        -0.252747
29     Nottinghamshire   147   150   194         0.319728
31     South Yorkshire   244   172   214        -0.122951
34              Surrey    98    27    33        -0.663265
35              Sussex   117    51    89        -0.239316
36       Thames Valley   210   118   146        -0.304762
37        Warwickshire    99    42    45        -0.545455

In [12]:
all_custody_df.iloc[:, -1]

1    -0.513889
2    -0.107527
5    -0.200000
7     0.017241
11   -0.537688
17   -0.053691
18   -0.204082
20   -0.168317
22   -0.459522
25   -0.252747
29    0.319728
31   -0.122951
34   -0.663265
35   -0.239316
36   -0.304762
37   -0.545455
Name: per_change_2014, dtype: float64

In [13]:
check_factsheets.main()

2025-09-25 15:14:05,572 - INFO - Loading sentence length data...
2025-09-25 15:14:05,591 - INFO - Loaded data from data/processed/PFA_custodial_sentences_all_FINAL.csv
2025-09-25 15:14:05,598 - INFO - Saving...
2025-09-25 15:14:05,617 - INFO - Data successfully saved to data/tests/factsheet_custodial_sentences_all.csv
2025-09-25 15:14:05,618 - INFO - Loading sentence length data...
2025-09-25 15:14:05,633 - INFO - Loaded data from data/processed/PFA_custodial_sentences_6_months_FINAL.csv
2025-09-25 15:14:05,645 - INFO - Saving...
2025-09-25 15:14:05,649 - INFO - Data successfully saved to data/tests/factsheet_custodial_sentences_6_months.csv
2025-09-25 15:14:05,649 - INFO - Loading offences data...
2025-09-25 15:14:05,672 - INFO - Loaded data from data/processed/PFA_custodial_sentences_by_offence_2024_FINAL.csv
2025-09-25 15:14:05,687 - INFO - Saving...
2025-09-25 15:14:05,695 - INFO - Data successfully saved to data/tests/factsheet_custodial_sentences_theft_offences.csv
2025-09-25 15:14:05,696 - INFO - Loading sentence type data...
2025-09-25 15:14:05,716 - INFO - Loaded data from data/processed/women_cust_comm_sus_FINAL.csv
2025-09-25 15:14:05,731 - INFO - Saving...
2025-09-25 15:14:05,739 - INFO - Data successfully saved to data/tests/factsheet_community_sentences.csv

In [7]:
check_factsheets.load_data(data_type='offence', year='2024').head()

2025-09-24 12:43:31,675 - INFO - Loading offences data...
2025-09-24 12:43:31,703 - INFO - Loaded data from data/processed/PFA_custodial_sentences_by_offence_2024_FINAL.csv

,pfa,year,offence,freq,plot_order,parent
0,Gloucestershire,2024,Assault of an emergency worker,1,2.0,Violence against the person
1,West Mercia,2024,Assault of an emergency worker,1,2.0,Violence against the person
2,Northamptonshire,2024,Assault of an emergency worker,2,2.0,Violence against the person
3,Dorset,2024,Assault of an emergency worker,3,2.0,Violence against the person
4,Leicestershire,2024,Assault of an emergency worker,3,2.0,Violence against the person

In [10]:
check_factsheets.load_data(data_type='sentence_length', sentence_length='6_months').head()

2025-09-24 12:58:41,233 - INFO - Loading sentence length data...

2025-09-24 12:58:41,245 - INFO - Loaded data from data/processed/PFA_custodial_sentences_6_months_FINAL.csv

,pfa,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,per_change_2014
0,Avon and Somerset,143,126,105,92,98,90,80,61,62,93,117,-0.181818
1,Bedfordshire,48,50,33,34,25,24,14,10,20,21,23,-0.520833
2,Cambridgeshire,55,56,84,82,89,60,44,32,45,56,58,0.054545
3,Cheshire,124,131,125,126,114,98,79,54,39,66,65,-0.475806
4,Cleveland,73,48,69,103,108,60,28,50,56,91,138,0.890411

In [5]:
check_factsheets.load_data(data_type='sentence_type')

2025-09-25 15:08:29,603 - INFO - Loading sentence type data...
2025-09-25 15:08:29,623 - INFO - Loaded data from data/processed/women_cust_comm_sus_FINAL.csv

                    pfa  year             outcome  freq
0     Avon and Somerset  2010  Community Sentence   619
1     Avon and Somerset  2010   Immediate Custody   178
2     Avon and Somerset  2010  Suspended Sentence   164
3     Avon and Somerset  2011  Community Sentence   730
4     Avon and Somerset  2011   Immediate Custody   209
...                 ...   ...                 ...   ...
1885          Wiltshire  2023   Immediate Custody    37
1886          Wiltshire  2023  Suspended Sentence    43
1887          Wiltshire  2024  Community Sentence   134
1888          Wiltshire  2024   Immediate Custody    32
1889          Wiltshire  2024  Suspended Sentence    56

[1890 rows x 4 columns]

In [25]:
df_community_sentences = check_factsheets.create_community_sentences_table(sample_pfas, time_period=10)
df_community_sentences

2025-09-25 14:37:15,523 - INFO - Loading sentence type data...
2025-09-25 14:37:15,565 - INFO - Loaded data from data/processed/women_cust_comm_sus_FINAL.csv

year              pfa             outcome  2014  2024  pct_change
0          Derbyshire  Community Sentence   274   233  -14.963504
1              Dorset  Community Sentence   112   117    4.464286
2              Durham  Community Sentence   168   129  -23.214286
3         Dyfed Powys  Community Sentence   148    79  -46.621622
4     Gloucestershire  Community Sentence   132   131   -0.757576
5           Hampshire  Community Sentence   466   413  -11.373391
6       Hertfordshire  Community Sentence   176    90  -48.863636
7                Kent  Community Sentence   408   445    9.068627
8          Lancashire  Community Sentence   522   398  -23.754789
9      Leicestershire  Community Sentence   203   167  -17.733990
10             London  Community Sentence  1758   930  -47.098976
11    South Yorkshire  Community Sentence   572   392  -31.468531
12             Surrey  Community Sentence   168   174    3.571429
13      Thames Valley  Community Sentence   419   349  -16.706444
14       Warwickshire  Community Sentence   205    68  -66.829268
15      West Midlands  Community Sentence   724   512  -29.281768