# Women's imprisonment
## Criminal Justice Statistics Police Force Area: Offences chart

In [1]:
%load_ext autoreload
%autoreload 2

## Testing `custody_offences.py`

In [2]:
from src.visualisation import custody_offences
from src.configuration import load_config

## Moving data processing steps to `filter_custody_offences.py` and testing

In [3]:
from src.data.processing import filter_custody_offences

In [4]:
config = load_config(2025)
df, max_year = filter_custody_offences.load_and_process_data(config=config)

2026-10-14 11:55:53,381 - INFO - Loading interim data for custody offences...
2026-10-14 11:55:54,244 - INFO - Loaded data from data/interim/2025/women_cust_comm_sus.csv
2026-10-14 11:55:54,830 - INFO - Filtering data for custodial sentences...
2026-10-14 11:55:54,842 - INFO - Starting data processing...
2026-10-14 11:55:54,844 - INFO - Filtering data from 2024 onwards
2026-10-14 11:55:54,848 - INFO - Grouping data by pfa, year, offence, specific_offence and summing frequencies...
2026-10-14 11:55:54,858 - INFO - Extracting 'Assault of an emergency worker' offence...
2026-10-14 11:55:54,860 - INFO - Grouping data by pfa, year, offence and summing frequencies...
2026-10-14 11:55:54,868 - INFO - Adding 'Assault of an emergency worker' offence to the main DataFrame...
2026-10-14 11:55:54,877 - INFO - Setting plot order for offences...
2026-10-14 11:55:54,880 - INFO - Creating filter for highlighted offence groups...
2026-10-14 11:55:54,883 - INFO - Setting parent column for offence groups...
2026-10-14 11:55:54,886 - INFO - Data processing complete.
2026-10-14 11:55:54,889 - INFO - Data successfully processed for PFA offences charts

In [5]:
df

,pfa,year,offence,freq,plot_order,parent
0,Gloucestershire,2024,Assault of an emergency worker,1,2.0,Violence against the person
1,West Mercia,2024,Assault of an emergency worker,1,2.0,Violence against the person
2,Northamptonshire,2024,Assault of an emergency worker,2,2.0,Violence against the person
3,Dorset,2024,Assault of an emergency worker,3,2.0,Violence against the person
4,Leicestershire,2024,Assault of an emergency worker,3,2.0,Violence against the person
...,...,...,...,...,...,...
463,Lancashire,2024,Violence against the person,52,2.0,All offences
464,West Midlands,2024,Violence against the person,55,2.0,All offences
465,South Wales,2024,Violence against the person,58,2.0,All offences
466,West Yorkshire,2024,Violence against the person,77,2.0,All offences
467,London,2024,Violence against the person,144,2.0,All offences

In [6]:
max_year

np.int64(2024)

In [7]:
df['offence'].value_counts()

offence
Theft offences                          42
Violence against the person             42
Assault of an emergency worker          40
Miscellaneous crimes against society    40
Public order offences                   40
Summary non-motoring                    40
Drug offences                           39
Fraud offences                          38
Possession of weapons                   37
Summary motoring                        32
Robbery                                 27
Criminal damage and arson               26
Sexual offences                         25
Name: count, dtype: int64

In [8]:
df['plot_order'].value_counts()

plot_order
0.0    305
2.0     82
1.0     42
3.0     39
Name: count, dtype: int64

## Back to testing `custody_offences.py`

Having issues with the trace creation. So digging into the code to see what's happening.

Debugging found that a stray `<br>` tag was being used in the labelling, which prevented the trace from being rendered.

New line tags `\n` were not breaking the lines anyway, so this will be an opportunity for developing a more robust solution. I'll remove all new line and break tags from the data processing for now, and pass them through a textwrap function when they're called for the trace construction.

In [9]:
df.query('pfa == "Avon and Somerset"')

,pfa,year,offence,freq,plot_order,parent
36,Avon and Somerset,2024,Assault of an emergency worker,25,2.0,Violence against the person
56,Avon and Somerset,2024,Criminal damage and arson,3,0.0,All other offences
88,Avon and Somerset,2024,Drug offences,9,3.0,All offences
105,Avon and Somerset,2024,Fraud offences,1,0.0,All other offences
158,Avon and Somerset,2024,Miscellaneous crimes against society,4,0.0,All other offences
211,Avon and Somerset,2024,Possession of weapons,7,0.0,All other offences
240,Avon and Somerset,2024,Public order offences,8,0.0,All other offences
303,Avon and Somerset,2024,Sexual offences,3,0.0,All other offences
338,Avon and Somerset,2024,Summary motoring,4,0.0,All other offences
380,Avon and Somerset,2024,Summary non-motoring,31,0.0,All other offences
409,Avon and Somerset,2024,Theft offences,46,1.0,All offences
458,Avon and Somerset,2024,Violence against the person,37,2.0,All offences

In [10]:
chart = custody_offences.test_chart(config=config)
chart

2026-10-14 11:55:55,322 - INFO - Loaded data from data/processed/2025/PFA_custodial_sentences_by_offence_2024_FINAL.csv
2026-10-14 11:55:55,378 - INFO - Creating filter for highlighted offence groups...
2026-10-14 11:55:55,717 - INFO - Adding chart annotations...
2026-10-14 11:55:55,721 - INFO - Setting source annotation...
2026-10-14 11:55:55,735 - INFO - Annotations added successfully.